In [3]:
import sys
!"{sys.executable}" -m pip install torch torchvision torchaudio

   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
    --------------------------------------- 1.6/123.0 MB 8.1 MB/s eta 0:00:16
   - -------------------------------------- 3.9/123.0 MB 9.7 MB/s eta 0:00:13
   -- ------------------------------------- 6.3/123.0 MB 10.4 MB/s eta 0:00:12
   -- ------------------------------------- 8.9/123.0 MB 10.8 MB/s eta 0:00:11
   --- ------------------------------------ 11.3/123.0 MB 11.0 MB/s eta 0:00:11
   ---- ----------------------------------- 13.6/123.0 MB 11.1 MB/s eta 0:00:10
   ----- ---------------------------------- 16.3/123.0 MB 11.2 MB/s eta 0:00:10
   ------ --------------------------------- 18.9/123.0 MB 11.2 MB/s eta 0:00:10
   ------ --------------------------------- 20.7/123.0 MB 11.3 MB/s eta 0:00:10
   ------- -------------------------------- 23.3/123.0 MB 11.2 MB/s eta 0:00:09
   -------- ------------------------------- 25.7/123.0 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 28.3/123.0 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Devendra kachhawa\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [4]:
import torch 
import torch.nn as nn 

In [5]:
# input 
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [7]:
neuron = nn.Linear(in_features=3, out_features=1)

In [8]:
output = neuron(inputs)

In [11]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [9]:
# verify ....... formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [10]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)