In [4]:
import torch 
import torch.nn as nn 

In [5]:
# input 
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [7]:
neuron = nn.Linear(in_features=3, out_features=1)

In [8]:
output = neuron(inputs)

In [11]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [9]:
# verify ....... formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [10]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)